"""Add resume_summary to users table

Revision ID: 9b02a4774cbd
Revises: eb7a33e6beee
Create Date: 2025-10-26 18:38:49.056893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b02a4774cbd'
down_revision: Union[str, Sequence[str], None] = 'eb7a33e6beee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume_summary')
    # ### end Alembic commands ###
